// <auto-generated />
namespace ShopList.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class subcatid : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(subcatid));
        
        string IMigrationMetadata.Id
        {
            get { return "201703031923468_subcatid"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
